### ISSUE TITLE
Streaming `stdin` and `stdout` in SSHClient

### ISSUE THREAD

**Issue by bummoblizard** [orlandos-nl/Citadel#24]
> The `executeCommand` function accumulated information into a contiguous `ByteBuffer`. This is useful for non-interactive commands such as `cat` and `ls`. Citadel currently does not expose APIs for streaming into a process' `stdin` or streaming the `stdout` elsewhere. If you want this, please create an issue.

We are planning to work on adding streaming support for Citadel as our [app](https://github.com/thebaselab/codeapp) requires the use of interactive commands (a shell). Would you shed some lights on how we might approach this? :)

**Comment by Joannis** [comment]
Hi @bummoblizard you shouldn't use `executeCommand` as a replacement for a _real_ TTY. But if you really don't care about the shell and its state, then you can use it for sure. Currently I don't offer a streaming API, but I'm happy to add it later.

**Comment by Joannis** [comment]
If you need this soon, I'd recommend making a PR, as I'm mostly focussed on customers right now.

**Comment by Joannis** [comment]
It's implemented now.
