### ISSUE TITLE
[Feature Request] Get notified when ssh connection was closed

### ISSUE THREAD

**Issue by AdrianDuan** [orlandos-nl/Citadel#25]
Hi, I'm using Citadel as SSH Client to connect a remote server, just want to know if there is anyway or API to get notified/callback when the connection was closed(by remote/network environment changed)?

**Comment by Joannis** [comment]
I don't think that this is currently an API I provide, I can add it though.

**Comment by Joannis** [comment]
I'm giving it a shot, but the unit tests seem to indicate NIO thinks the connection is still active. Not sure why et.

**Comment by Joannis** [comment]
I've added an `.onDisconnect` API on `client`
