### ISSUE TITLE
iOS 14 support

### ISSUE THREAD

**Issue by waylybaye** [orlandos-nl/Citadel#27]
Hi Joannis, great job on this library! I'm wondering why you set the iOS 15 as minimum deployment target, I tried to change it to iOS 14 and it works as expected on iOS 14.

**Comment by Joannis** [comment]
I didn't test this on iOS 14, and don't currently offer NIOTS support out of the box. Finally, when I initially created Citadel there was no async-await yet. But when I initially moved over to async-await, iOS 13 and 14 did not yet have async-await backported.

**Comment by Joannis** [comment]
Feel free to make a PR though

**Comment by waylybaye** [comment]
Thanks, closed according to #29
