### ISSUE TITLE
Support custom SSHAuthenticationMethod

### ISSUE THREAD

**Issue by waylybaye** [orlandos-nl/Citadel#28]
I would like to suggest adding support for custom `SSHAuthenticationMethod`. Currently, I need to provide multiple authentication methods for one SSH connection, such as auto-attempting all available keys or implementing two-factor login. It would be great if `SSHClient.connect` could use `NIOSSHClientUserAuthenticationDelegate` as a generic parameter so that users can implement their own authentication logic.

**Comment by Joannis** [comment]
I agree, thanks for the issue.

**Comment by Joannis** [comment]
Implemented to be merged bundled with #26

**Comment by waylybaye** [comment]
Great news! I have tested the branch, and it works perfectly. However, I did encounter an issue when testing 2-factor login, as `swift-nio-ssh` currently does not support keyboard-interactive authentication. If I have the time, I will attempt to make a pull request to address this issue. Thank you for your efforts in developing this feature!

**Comment by Joannis** [comment]
Sounds good! Let me know if you need any tips for that. I'm closely involved with NIOSSH as well, and can bring up the topic with cory this week.

**Comment by Joannis** [comment]
I'll close this one for now, in favour of #30
