### ISSUE TITLE
Support shell channel

### ISSUE THREAD

**Issue by waylybaye** [orlandos-nl/Citadel#32]
Hi Joannis, Do you have any plans to support a shell channel? I noticed that you already support streaming in executeCommand, and it would be really cool if you could also support a shell channel. Thank you!

**Comment by Joannis** [comment]
I want to, but don't have a personal need for it. So I won't be spending my own development hours on it until there's a demand from a customer or an existing PR.

**Comment by Joannis** [comment]
@waylybaye if you're looking to implement a shell channel, please reach out to me on Discord. I'm checking it out, but it's not easy to set an API in stone without extensive practical use.

**Comment by Marcocanc** [comment]
@waylybaye Would #36 work for you?
