### ISSUE TITLE
TTY executing function may stuck forever when inShell is true

### ISSUE THREAD

**Issue by owenzhao** [orlandos-nl/Citadel#49]
<img width="932" alt="截屏2023-10-20 23 46 52" src="https://github.com/orlandos-nl/Citadel/assets/2182896/f77568be-1fdd-49d0-a5e9-e6a107caec68">

TTY added ";exit\n" in its code. However, if a command has already ended with ";", a parse error of ";;" is risen and the in shell can't quit. 

Since the in shell is not quit, the app calls this api won't get the buffer and the app waits forever.

related function: 

```swift
public func executeCommand(_ command: String, maxResponseSize: Int = .max, mergeStreams: Bool = false, inShell: Bool = false) async throws -> ByteBuffer
```

Try: "ls abc;" as command.

**Comment by owenzhao** [comment]
How about "\\\n;exit\n"? I worked in zsh with "ls abc" with or without ";" at the end.

**Comment by Joannis** [comment]
That's a good solution :)
