### ISSUE TITLE
Buffering/backpressure issue

### ISSUE THREAD

**Issue by finestructure** [orlandos-nl/Citadel#62]
As discussed on Slack, there seems to be an issue around buffering or back pressure support when logging output from Citadel.

I'm running a task as follows:

```swift
        let stream = try await executeCommandStream("script.sh", inShell: true)
        for try await output in stream {
            switch output {
                case let .stdout(buffer):
                    print(String(buffer: buffer), terminator: "")
                case let .stderr(buffer):
                    print(String(buffer: buffer), terminator: "")
            }
        }
```

where "script.sh" is a simple

```sh
echo "❌  this must fail"
exit 1
```

but the echo isn't showing up in the logs.

An ugly fix for this is to introduce a delay before exiting:

```sh
echo "❌  this must fail"
sleep 0.1
exit 1
```

Best I can tell, there's no way on the consumer side of the `AsyncThorwingStream` to ensure all messages have been delivered before the stream terminates.

**Comment by Joannis** [comment]
Probably related to another issue I've seen: `exit` can be send before the remainder of data was written, resulting in misinterpretation in Citadel. This is now fixed.
