### ISSUE TITLE
SFTP write error

### ISSUE THREAD

**Issue by JBergsee** [orlandos-nl/Citadel#64]
**Describe the bug**
The write file example produces an error:

2024-04-16T13:21:15+0400 info nl.orlandos.citadel.sftp : [Citadel] SFTP connection opened and ready
2024-04-16T13:21:15+0400 info nl.orlandos.citadel.sftp : [Citadel] SFTP requesting to open file at '/flightbriefing/file.txt' with flags 0x00000023
(lldb) po error
▿ {1}(code: SSH_FX_NO_SUCH_FILE, #'No such file')
  - requestId : 1
  - errorCode : SSH_FX_NO_SUCH_FILE
  - message : "No such file"
  - languageTag : ""

**Reproducer Sample**
```
 func testDirectWriting() async throws {
        guard let data = "Hello world".data(using: .utf8) else {
            XCTFail()
            return
        }

        do {
            let file = try await sut?.sftp?.openFile(filePath: "/flightbriefing/file.txt", flags: [.read, .write, .forceCreate])
            try await file?.write(ByteBuffer(data: data), at: 0)
            try await file?.close()
        } catch {
            print(error)
            XCTFail()
        }
    }
```
(Where sftp is an SSHClient.SFTPClient)

**Expected behavior**
The file should be written (even if it does not exist as the .forceCreate flag is there). No error should be thrown.

**Client (please complete the following information):**
 - Xcode 15.3
 - Client: Citadel via SPM
- Version of Citadel, if applicable: 0.7.1

**Comment by Joannis** [comment]
I expect this to be a documentation issue. Can you try removing the `.read` flag?

**Comment by JBergsee** [comment]
Disregard!
If anybody ever has this problem, please be aware that when writing to (or reading from) a subdirectory, the path must not start with a slash "/"!

**Comment by Joannis** [comment]
Happy to hear you've found it! Thanks for making issues, and also for updating the issue, so that I don't crack my brain on this.

**Comment by sssilver** [comment]
I'm running into the same issue, however I'm confused about what "the path must not start with a slash" means.

My code:

```swift
func uploadUsingSFTP(content: String, remoteHost: String, remotePath: String, username: String, password: String) async throws {
    let client = try await SSHClient.connect(
        host: remoteHost,
        authenticationMethod: .passwordBased(username: username, password: password),
        hostKeyValidator: .acceptAnything(), // TODO: Use a secure validator in production
        reconnect: .never
    )

    let sftp = try await client.openSFTP()

    // Open or create a remote file for writing
    let remoteFile = try await sftp.openFile(filePath: remotePath, flags: [.create, .truncate])

    try await remoteFile.write(ByteBuffer(data: content.data(using: .utf8)!), at: 0)

    try await remoteFile.close()
    try await client.close()
}
```

I tried passing anything to `remotePath`: `/home/user/file.html`, `file.html` -- everything results in the same error:

```
2024-10-01T03:58:20-0500 info nl.orlandos.citadel.sftp : [Citadel] SFTP connection opened and ready
2024-10-01T03:58:20-0500 info nl.orlandos.citadel.sftp : [Citadel] SFTP requesting to open file at 'file.html' with flags 0x00000018
2024-10-01T03:58:38-0500 warning nl.orlandos.citadel.sftp : [Citadel] SFTPFile deallocated without being closed first
Error uploading HTML file: {2}(code: SSH_FX_NO_SUCH_FILE, #'No such file')
```

What am I missing?

**Comment by Joannis** [comment]
The `.write` flag was missing from the `openFile` call
