### ISSUE TITLE
error: no such module 'CryptoKit' on Linux

### ISSUE THREAD

**Issue by RaesakAce** [orlandos-nl/Citadel#69]
When building Citadel 0.7.3 on Linux compilation fails with

```
~/repos/Citadel/Sources/Citadel/Client.swift:2:8: error: no such module 'CryptoKit'
import CryptoKit
       ^
error: fatalError
```
just running

```
swift package update
```
and

```
swift build
```

Tested on Ubuntu 22, Amazon Linux 2, and ArchLinux with RHEL 9 toolchain.

**Comment by Joannis** [comment]
Thanks for the heads up, that's regression I didn't spot since I only tested that change on macOS. Sorry about that. I'm tagging it in a minute as 0.7.4
