### ISSUE TITLE
Error while connecting to SFTP

### ISSUE THREAD

**Issue by obliqueRotationMethod** [orlandos-nl/Citadel#7]
Trying to connect to an SFTP server with the following config:
```
    let ssh = try await SSHClient.connect (
        host: "sftp012.successfactors.eu",
        authenticationMethod: .passwordBased(username: "UUUU", password: "PPPP"),
        hostKeyValidator: .acceptAnything(),
        reconnect: .never )
```

Receiving the following error:
Citadel.ClientHandshakeHandler.(unknown context at $10122d328).(unknown context at $10122d3a4).AuthenticationFailed error 1.

Connection to this server via an SFTP client like CyberDuck works fine. 
Connecting via Citadel to this sftp Testserver works fine https://www.sftp.net/public-online-sftp-servers

Help would be much appreciated :)

**Comment by Joannis** [comment]
AuthenticationFailed only happens when either authentication fails or it takes a really long time to log in. Could that second case be what's happening?

**Comment by obliqueRotationMethod** [comment]
Hey, thanks for your reply

It takes about 5 - 10 seconds till this error above is thrown. Regardless if username/ password are correct or not
Tested the server [with this tool](https://sshcheck.com/) and saw that it only offers an ssh-rsa host key. Figured that this may cause an issue?

**Comment by Joannis** [comment]
Could be, you'll need to enable SSH-RSA support in Citadel then. I assume you _are_ sending over your RSA key for authentication right?

**Comment by obliqueRotationMethod** [comment]
Aww sorry I confused that part with the ssh-rsa host key. No, I want to authenticate to this server using username/ pw.
I do not have any RSA key for this one. At least for other SFTP clients I do not need one for an connection

**Comment by Joannis** [comment]
Closing this as it's stale, and it's being actively used. Should there be any questions regarding such errors in the future, reach out to me again :)
