### ISSUE TITLE
Added pseudo-terminal control parameters

### ISSUE THREAD

**Issue by alien10086** [orlandos-nl/Citadel#78]
I tried using the Citadel library and swiftterm together to implement an SSH client, but I couldn't find a way to pass the "term_modes" parameter, which is used to display relevant information in a terminal emulator. Is there a plan to add this parameter in the future? Or if I want to add this functionality, where should I start?

**Comment by alien10086** [comment]
Hello yesterday I discussed this with joannis on discord and I tried to modify the withTTY call method in the fork branch to work perfectly with swiftterm, like this
`@available(macOS 15.0, *)
    public func withTTY(
        envRequests: [SSHChannelRequestEvent.EnvironmentRequest] = [],
        ptyRequset: SSHChannelRequestEvent.PseudoTerminalRequest? = nil,
        perform: (_ inbound: TTYOutput, _ outbound: TTYStdinWriter) async throws -> Void
    ) async throws {
        let (channel, output) = try await _shellExecuteCommandStream(envRequests:envRequests, ptyRequset:ptyRequset)

        func close() async throws {
            try await channel.close()
        }

        do {
            let inbound = TTYOutput(sequence: output)
            try await perform(inbound, TTYStdinWriter(channel: channel))
            try await close()
        } catch {
            try await close()
            throw error
        }
    }`
`
internal func _shellExecuteCommandStream(
        envRequests: [SSHChannelRequestEvent.EnvironmentRequest] = [],
        ptyRequset: SSHChannelRequestEvent.PseudoTerminalRequest? = nil
    ) async throws -> (channel: Channel, output: AsyncThrowingStream<ExecCommandOutput, Error>) {
        let (stream, streamContinuation) = AsyncThrowingStream<ExecCommandOutput, Error>.makeStream()
        
        var hasReceivedChannelSuccess = false
        var exitCode: Int?
        
        let handler = ExecCommandHandler(logger: logger) { channel, output in
            switch output {
            case .stdout(let stdout):
                streamContinuation.yield(.stdout(stdout))
            case .stderr(let stderr):
                streamContinuation.yield(.stderr(stderr))
            case .eof(let error):
                if let error {
                    streamContinuation.finish(throwing: error)
                } else if let exitCode, exitCode != 0 {
                    streamContinuation.finish(throwing: CommandFailed(exitCode: exitCode))
                } else {
                    streamContinuation.finish()
                }
            case .channelSuccess:
                if !hasReceivedChannelSuccess {
            //         if let command {
            //             let commandData = SSHChannelData(
            //                 type: .channel,
            //                 data: .byteBuffer(ByteBuffer(string: command + ";exit\n"))
            //             )
            //             channel.writeAndFlush(commandData, promise: nil)
            //         }
                    hasReceivedChannelSuccess = true
                }
            case .exit(let status):
                exitCode = status
            }
        }
        
        let channel = try await eventLoop.flatSubmit {
            let createChannel = self.eventLoop.makePromise(of: Channel.self)
            self.session.sshHandler.createChannel(createChannel) { channel, _ in
                channel.pipeline.addHandlers(handler)
            }
            
            self.eventLoop.scheduleTask(in: .seconds(15)) {
                createChannel.fail(CitadelError.channelCreationFailed)
            }
            
            return createChannel.futureResult
        }.get()
        

        for envRequest in envRequests {
            try await channel.triggerUserOutboundEvent(envRequest)
        }
     
        
        if let ptyrequset = ptyRequset {
            try await channel.triggerUserOutboundEvent(ptyrequset)
        }
        
        try await channel.triggerUserOutboundEvent(SSHChannelRequestEvent.ShellRequest(
            wantReply: true
        ))
        
        return (channel, stream)
    }
`

Do this at call time
`
class SSHTerminalViewManage {
    static let shared = SSHTerminalViewManage()

    private init() {
  
    }

    var sshTermInstance: SshTerminalView?

    public func getSSHTerminalView(client: SSHClient) -> SshTerminalView {
        if let sshTermInstance = sshTermInstance {
            return sshTermInstance
        }
        let sshterm = SshTerminalView(frame: NSRect.zero)
        sshTermInstance = sshterm
        Task {
            try await client.withTTY(
                envRequests:[SSHChannelRequestEvent.EnvironmentRequest(wantReply: true, name: "LANG", value: "en_US.UTF-8")],
                ptyRequset: SSHChannelRequestEvent.PseudoTerminalRequest(
                    wantReply: true,
                    term: "xterm",
                    terminalCharacterWidth: 80,
                    terminalRowHeight: 24,
                    terminalPixelWidth: 0,
                    terminalPixelHeight: 0,
                    terminalModes: .init([.ECHO: 1]) 
                )

            ) {
                ttyOutput, ttyStdinWriter in
                await sshterm.seTtyStdin(ttyStdinWriter)
                try await withThrowingTaskGroup(of: Void.self) { group in

                    group.addTask {
                        for try await value in ttyOutput {
                            switch value {
                            case let .stdout(stdout):
                                var mutableStdout = stdout
                                if let bytes = mutableStdout.readBytes(length: mutableStdout.readableBytes) {
                                    // debugPrint(bytes)
                                    let byteArray: ArraySlice<UInt8> = bytes[...]
                                    await sshterm.feed(byteArray: byteArray)
                                }

                            case let .stderr(stderr):
                                var mutableStderr = stderr
                                if let bytes = mutableStderr.readBytes(length: mutableStderr.readableBytes) {
                                    // debugPrint(bytes)
                                    let byteArray: ArraySlice<UInt8> = bytes[...]
                                    await sshterm.feed(byteArray: byteArray)
                                }
                            }
                        }
                    }

                    try await group.next()
                    group.cancelAll()
                }
            }
        }
        return sshterm
    }
}
`
This allows arbitrary Settings to be passed in at call time based on the user's needs, which worked perfectly in my requirements scenario. Of course, I'm just a beginner in swift. Is it possible to design an api this way?

**Comment by Joannis** [comment]
I've updated the PR to have a `withPTY` call
