### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Freelenzer** [orlandos-nl/Citadel#81]
**Describe the bug**

The build seems to fail with the newest release.
Due to an async defer statement.

https://github.com/orlandos-nl/Citadel/issues/81

This seems to be a possible fix:

https://stackoverflow.com/a/73093428/7289678

**Reproducer Sample**
Code that reproduces the issue. Omit credentials.

**Expected behavior**

**Client (please complete the following information):**
 - OS: [e.g. iOS, macOS Sonoma, Ubuntu 23.04]
 - Client: [e.g. openssh, Citadel]
- Version of Citadel, if applicable:

**Server (please complete the following information):**
 - OS: [ Ubuntu 23.04]
 - Server: [e.g. opensshd, Citadel]
- Version of Citadel, if applicable: 0.9.0

**Additional context**

`Citadel/Sources/Citadel/SFTP/Client/SFTPClient.swift:326:25: error: 'async' call cannot occur in a defer body
           try? client.close()
 error: fatalError
`

**Comment by Joannis** [comment]
Sorry about this!
